sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.mongodb-binaries
notifications:
  email: true
node_js:
  - "10"
  - "8"
script:
  - yarn run lint
  - yarn run test && codecov
