version: '3'
services:
  api:
    build: .
    environment:
      NODE_ENV: 'development'
      PORT: 4001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
